In [2]:
import numpy as np
import pandas as pd

In [3]:
import requests

url = 'https://huggingface.co/datasets/bitext/Bitext-customer-support-llm-chatbot-training-dataset/embed/viewer/default/train'

response = requests.get(url)

In [4]:
df = pd.read_csv("hf://datasets/bitext/Bitext-customer-support-llm-chatbot-training-dataset/Bitext_Sample_Customer_Support_Training_Dataset_27K_responses-v11.csv")

In [5]:
df[['instruction']].sample(10)

                                             instruction
21957  need assistance to write a review about ur copany
12291                       d uship to {{Delivery City}}
340        I need help cancelling oredr {{Order Number}}
14409                 editing details on premium account
743     can uhelp me to cancel purchase {{Order Number}}
22977  I do not know how to submit the new shipping a...
19823                I don't know how to shop an article
21229                     report issues creating account
8057   I want to check what hours customer support av...
23597  i have got to set up my secondary deliver address

In [8]:
question_words = r"\b(what|where|when|who|whose|which|why|how)\b"

question_df = df[
    df["instruction"].str.contains(
        question_words,
        case=False,
        na=False,
        regex=True
    )
]

question_df[["instruction"]].sample(10)

/tmp/ipykernel_58/1845462708.py:4: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df["instruction"].str.contains(

                                             instruction
15401  what do Ihave to do to download my invoice #85...
14925  I don't know how I can get my goddamn invoice ...
22340           i do not know how i can leave an opinion
24847  what do I have to do to change to the {{Accoun...
4052    how do I look for my bills from {{Person Name}}?
25751  how to see order {{Order Number}} current status?
13292  where to check how soon can I expect my product ?
10965  what do i have to do to delete my {{Account Ty...
15939            how do i demand a compensation of money
8036   where to check at what time I can reach custom...

In [9]:
final_df = question_df[["instruction"]].sample(1000, random_state = 42)

In [10]:
final_df.head()

                                             instruction
9340                  how can i talk with an human agent
6444   i have to check how long reimbursements take i...
14770  i do not know how i can edit the personal details
8817   how can I check what hours I can call customer...
8371    I don't know what to do to call customer service

In [11]:
final_df.to_csv('questions.csv')